name: Build Changed Packages
description: Build uniquement les packages qui ont des changements.

inputs:
  auth-package:
    description: true si auth-package doit être buildé
    required: true

runs:
  using: composite
  steps:
    - name: Build auth-package
      if: inputs.auth-package == 'true'
      shell: bash
      run: pnpm --filter @57eme-regiment/auth-package build
